version: '3.9'

services:
  web:
    build: ./gunicorn
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./gunicorn/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=useradmin
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=stock_interest_metric_db

  server:
    container_name: server_1
    build: ./server
    command: python entry.py
    volumes:
      - ./server:/server/
    expose:
      - 4443

  cron:
    container_name: cron
    build: ./cron
    volumes:
      - ./gunicorn/:/usr/src/app/
    env_file:
      - ./.env.dev
    command: /cron/entrypoint.sh

volumes:
  postgres: