# Generated by Django 4.0.4 on 2022-05-24 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_admincontactmessage_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admincontactmessage',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 22, 5, 37, 511704)),
        ),
        migrations.AlterField(
            model_name='apicalls',
            name='time_called',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 22, 5, 37, 510703)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 22, 5, 37, 511204)),
        ),
        migrations.AlterField(
            model_name='setaccountfordelete',
            name='delete_click_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 22, 5, 37, 511204)),
        ),
        migrations.AlterField(
            model_name='setaccountfordelete',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 22, 5, 37, 511204)),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='message_content',
            field=models.CharField(max_length=400),
        ),
    ]
