# Generated by Django 4.0.4 on 2022-05-24 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_admincontactmessage_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessages',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 22, 24, 14, 677194)),
        ),
        migrations.AddField(
            model_name='usermessages',
            name='message_title',
            field=models.CharField(default='title', max_length=50),
        ),
        migrations.AlterField(
            model_name='admincontactmessage',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 22, 24, 14, 677694)),
        ),
        migrations.AlterField(
            model_name='apicalls',
            name='time_called',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 22, 24, 14, 676694)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 22, 24, 14, 677694)),
        ),
        migrations.AlterField(
            model_name='setaccountfordelete',
            name='delete_click_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 22, 24, 14, 677194)),
        ),
        migrations.AlterField(
            model_name='setaccountfordelete',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 25, 22, 24, 14, 677194)),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='message_content',
            field=models.CharField(default='message', max_length=300),
        ),
    ]
