# Generated by Django 4.0.4 on 2022-05-30 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_remove_userapi_active_alter_admincontactmessage_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllUsersMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_date', models.DateTimeField(default=datetime.datetime(2022, 5, 30, 18, 59, 30, 598064))),
                ('message_title', models.CharField(default='title', max_length=50)),
                ('message_content', models.CharField(default='message', max_length=300)),
                ('archived', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'all_user_messages',
            },
        ),
        migrations.AddField(
            model_name='usermessages',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admincontactmessage',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 18, 59, 30, 599064)),
        ),
        migrations.AlterField(
            model_name='apicalls',
            name='time_called',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 18, 59, 30, 597564)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 18, 59, 30, 598564)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 30, 18, 59, 30, 598564)),
        ),
        migrations.AlterField(
            model_name='resetemailentry',
            name='time_made',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 18, 59, 30, 599064)),
        ),
        migrations.AlterField(
            model_name='setaccountfordelete',
            name='delete_click_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 18, 59, 30, 598564)),
        ),
        migrations.AlterField(
            model_name='setaccountfordelete',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 31, 18, 59, 30, 598564)),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 18, 59, 30, 598064)),
        ),
    ]
