# Generated by Django 4.0.4 on 2022-06-02 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_apicalls_is_counted_alter_admincontactmessage_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resetemailentry',
            name='redeemed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='admincontactmessage',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 15, 10, 34, 802155)),
        ),
        migrations.AlterField(
            model_name='allusersmessages',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 15, 10, 34, 801655)),
        ),
        migrations.AlterField(
            model_name='apicalls',
            name='time_called',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 15, 10, 34, 801155)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 15, 10, 34, 802155)),
        ),
        migrations.AlterField(
            model_name='payments',
            name='payment_expiry',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 2, 15, 10, 34, 802155)),
        ),
        migrations.AlterField(
            model_name='resetemailentry',
            name='time_made',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 15, 10, 34, 802655)),
        ),
        migrations.AlterField(
            model_name='setaccountfordelete',
            name='delete_click_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 15, 10, 34, 801655)),
        ),
        migrations.AlterField(
            model_name='setaccountfordelete',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 3, 15, 10, 34, 801655)),
        ),
        migrations.AlterField(
            model_name='usermessages',
            name='message_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 2, 15, 10, 34, 801155)),
        ),
    ]
